apiVersion: apps/v1
kind: Deployment
metadata:
  name: gladen-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gladen-web
  template:
    metadata:
      labels:
        app: gladen-web
    spec:
      containers:
        - name: gladen-web-pod
          image: gladen-web
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gladen-web-service
spec:
  selector:
    app: gladen-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /testpath
            pathType: Prefix
            backend:
              serviceName: test
              servicePort: 80

